"""Commit PR node — commits changes, pushes branch, and opens a GitHub PR."""

import logging
import subprocess

logger = logging.getLogger(__name__)


def _run(cmd: list[str], cwd: str | None = None, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=cwd,
        text=True,
        check=True,
        capture_output=capture,
    )


def make_commit_pr_node() -> callable:
    """Create a commit_pr_node that commits changes, pushes branch, and opens a PR."""
    
    def commit_pr_node(state: dict) -> dict:
        """Commit changes, push branch, and open a GitHub PR."""
        repo_path = state.get("repo_path", ".")
        branch_name = state.get("branch_name", "issue-fix")
        issue_number = state.get("issue_number")
        issue_title = state.get("issue_title", "Fix issue")
        issue_url = state.get("issue_url", "")
        completed_tasks = state.get("completed_tasks", [])

        logger.info("commit_pr_start", extra={"branch": branch_name, "completed": len(completed_tasks)})

        try:
            try:
                _run(["git", "checkout", "-b", branch_name], cwd=repo_path)
            except subprocess.CalledProcessError:
                logger.warning("branch_exists_checking_out", extra={"branch": branch_name})
                _run(["git", "checkout", branch_name], cwd=repo_path)

            _run(["git", "add", "-A"], cwd=repo_path)

            status = _run(["git", "status", "--porcelain"], cwd=repo_path, capture=True)
            if not status.stdout.strip():
                logger.warning("nothing_to_commit")
                return {"errors": ["No changes to commit"], "phase": "commit_pr"}

            commit_msg = f"fix: resolve issue #{issue_number} — {issue_title}"
            if issue_url:
                commit_msg += f"\n\nCloses {issue_url}"

            _run(["git", "commit", "-m", commit_msg], cwd=repo_path)

            sha_result = _run(["git", "rev-parse", "HEAD"], cwd=repo_path, capture=True)
            commit_sha = sha_result.stdout.strip()

            _run(["git", "push", "-u", "origin", branch_name], cwd=repo_path)

            task_lines = "\n".join(f"- {t}" for t in completed_tasks) if completed_tasks else "- See commit for details"
            pr_body = f"Resolves #{issue_number}\n\n## Changes\n{task_lines}\n\n Generated by issue_to_pr workflow"

            pr_result = _run(
                ["gh", "pr", "create",
                 "--title", f"fix: {issue_title}",
                 "--body", pr_body,
                 "--head", branch_name],
                cwd=repo_path,
                capture=True,
            )
            pr_url = pr_result.stdout.strip()

            logger.info("commit_pr_done", extra={"pr_url": pr_url, "commit_sha": commit_sha})

            return {
                "pr_url": pr_url,
                "commit_sha": commit_sha,
                "phase": "commit_pr",
            }

        except subprocess.CalledProcessError as exc:
            logger.error("commit_pr_failed", extra={"error": str(exc), "stderr": exc.stderr or ""})
            return {"errors": [f"commit_pr failed: {exc}"], "phase": "commit_pr"}

    return commit_pr_node
