#!/usr/bin/env bash
# Maestro Infrastructure — One-command setup
# Installs Docker if needed, generates secrets, starts the observability stack.
#
# Usage:
#   ./infrastructure/setup.sh          # Full setup
#   ./infrastructure/setup.sh --check  # Just check prerequisites
set -euo pipefail

cd "$(dirname "$0")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[+]${NC} $*"; }
warn()  { echo -e "${YELLOW}[!]${NC} $*"; }
error() { echo -e "${RED}[x]${NC} $*"; }

# ── Step 1: Check / Install prerequisites ────────────────────────────

check_brew() {
    if ! command -v brew &>/dev/null; then
        error "Homebrew not found. Install from https://brew.sh"
        exit 1
    fi
}

install_docker() {
    if command -v docker &>/dev/null && docker info &>/dev/null; then
        info "Docker is running"
        return 0
    fi

    # Check for Docker CLI
    if ! command -v docker &>/dev/null; then
        warn "Docker not found. Installing via Homebrew..."
        check_brew
        brew install docker docker-compose
        info "Docker CLI installed"
    fi

    # Check for a Docker runtime (Colima, Docker Desktop, or other)
    if ! docker info &>/dev/null; then
        if command -v colima &>/dev/null; then
            info "Starting Colima..."
            colima start --memory 4 --cpu 4
        elif [ -d "/Applications/Docker.app" ]; then
            info "Starting Docker Desktop..."
            open -a Docker
            echo -n "Waiting for Docker Desktop..."
            for i in $(seq 1 30); do
                if docker info &>/dev/null; then echo " ready"; break; fi
                [ "$i" -eq 30 ] && { echo " timeout"; error "Docker Desktop didn't start in 60s. Open it manually."; exit 1; }
                sleep 2; echo -n "."
            done
        else
            warn "No Docker runtime found. Installing Colima..."
            check_brew
            brew install colima
            info "Starting Colima..."
            colima start --memory 4 --cpu 4
        fi
    fi

    # If docker context doesn't work, try Colima socket directly
    if ! docker info &>/dev/null; then
        local colima_sock="$HOME/.colima/default/docker.sock"
        if [ -S "$colima_sock" ]; then
            export DOCKER_HOST="unix://$colima_sock"
            info "Using Colima socket: $colima_sock"
        fi
    fi

    if ! docker info &>/dev/null; then
        error "Docker daemon not reachable. Check your Docker installation."
        exit 1
    fi
    info "Docker is running"
}

check_docker_compose() {
    if docker compose version &>/dev/null; then
        COMPOSE="docker compose"
        info "Docker Compose available (plugin)"
    elif command -v docker-compose &>/dev/null; then
        COMPOSE="docker-compose"
        info "docker-compose available (standalone)"
    else
        warn "Docker Compose not found. Installing..."
        check_brew
        brew install docker-compose
        COMPOSE="docker-compose"
    fi
    export COMPOSE
}

# ── Step 2: Generate .env with secrets ───────────────────────────────

generate_env() {
    if [ -f .env ]; then
        info ".env already exists — skipping generation"
        return 0
    fi

    info "Generating .env with random secrets..."
    local nextauth_secret encryption_key pg_pass ch_pass redis_pass minio_pass admin_pass

    nextauth_secret=$(openssl rand -base64 32)
    encryption_key=$(openssl rand -hex 32)
    pg_pass=$(openssl rand -base64 16 | tr -d '=/+')
    ch_pass=$(openssl rand -base64 16 | tr -d '=/+')
    redis_pass=$(openssl rand -base64 16 | tr -d '=/+')
    minio_pass=$(openssl rand -base64 16 | tr -d '=/+')
    admin_pass=$(openssl rand -base64 12 | tr -d '=/+')
    salt=$(openssl rand -base64 32)

    cat > .env << EOF
# Auto-generated by setup.sh — $(date -Iseconds)
# Langfuse Auth
NEXTAUTH_SECRET=${nextauth_secret}
SALT=${salt}
ENCRYPTION_KEY=${encryption_key}
NEXTAUTH_URL=http://localhost:3100

# Langfuse Init Project (auto-created on first boot)
LANGFUSE_INIT_PUBLIC_KEY=pk-lf-maestro
LANGFUSE_INIT_SECRET_KEY=sk-lf-maestro
LANGFUSE_ADMIN_EMAIL=admin@local.dev
LANGFUSE_ADMIN_PASSWORD=${admin_pass}

# Postgres
POSTGRES_USER=langfuse
POSTGRES_PASSWORD=${pg_pass}
POSTGRES_DB=langfuse

# ClickHouse
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${ch_pass}

# Redis
REDIS_PASSWORD=${redis_pass}

# MinIO
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${minio_pass}

# Grafana
GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=${admin_pass}
GRAFANA_ROOT_URL=http://localhost:3200
EOF

    info ".env generated with random passwords"
}

# ── Step 3: Start the stack ──────────────────────────────────────────

start_stack() {
    # Source .env
    set -a; source .env; set +a

    # Idempotency check
    if curl -sf "http://localhost:3100/api/public/health" &>/dev/null; then
        info "Stack already running"
        return 0
    fi

    # Port conflict check
    local conflict=0
    for port in 3100 3200 5432 8123 9000 9091; do
        if lsof -i :"$port" &>/dev/null; then
            warn "Port $port already in use"
            conflict=1
        fi
    done
    [ "$conflict" -eq 1 ] && warn "Some ports are in use — stack may fail to start"

    info "Starting stack (this may take 1-2 minutes on first run)..."
    $COMPOSE up -d

    # Wait for Langfuse
    echo -n "Waiting for Langfuse..."
    for i in $(seq 1 60); do
        if curl -sf "http://localhost:3100/api/public/health" &>/dev/null; then
            echo " ready"; break
        fi
        [ "$i" -eq 60 ] && { echo " TIMEOUT"; error "Langfuse didn't start in 120s. Check: docker compose logs langfuse-web"; exit 1; }
        sleep 2; echo -n "."
    done

    # Wait for Grafana
    echo -n "Waiting for Grafana..."
    for i in $(seq 1 20); do
        if curl -sf "http://localhost:3200/api/health" &>/dev/null; then
            echo " ready"; break
        fi
        [ "$i" -eq 20 ] && echo " (still starting — check http://localhost:3200)"
        sleep 2; echo -n "."
    done
}

# ── Step 4: Print summary ───────────────────────────────────────────

print_summary() {
    echo ""
    echo "┌──────────────────────────────────────────────────────────┐"
    echo "│              Maestro Observability Stack                 │"
    echo "├──────────────┬──────────────────────┬───────────────────┤"
    echo "│ Service      │ URL                  │ Credentials       │"
    echo "├──────────────┼──────────────────────┼───────────────────┤"
    echo "│ Langfuse     │ http://localhost:3100 │ See .env          │"
    echo "│ Grafana      │ http://localhost:3200 │ admin / (in .env) │"
    echo "│ Prometheus   │ http://localhost:9091 │                   │"
    echo "│ ClickHouse   │ http://localhost:8123 │                   │"
    echo "└──────────────┴──────────────────────┴───────────────────┘"
    echo ""
    echo "To connect your workflows to Langfuse, export these env vars:"
    echo ""
    echo "  export LANGFUSE_BASE_URL=http://localhost:3100"
    echo "  export LANGFUSE_PUBLIC_KEY=pk-lf-maestro"
    echo "  export LANGFUSE_SECRET_KEY=sk-lf-maestro"
    echo ""
    echo "Then run a workflow:"
    echo "  maestro run chain_of_thought --task 'Your question here'"
    echo ""
    echo "To stop: ./infrastructure/stop.sh"
}

# ── Main ─────────────────────────────────────────────────────────────

if [ "${1:-}" = "--check" ]; then
    echo "Checking prerequisites..."
    command -v docker &>/dev/null && info "docker: found" || error "docker: not found"
    docker info &>/dev/null && info "docker daemon: running" || warn "docker daemon: not running"
    docker compose version &>/dev/null && info "docker compose: found" || warn "docker compose: not found"
    command -v curl &>/dev/null && info "curl: found" || error "curl: not found"
    [ -f .env ] && info ".env: exists" || warn ".env: not found (will be generated)"
    exit 0
fi

echo "═══════════════════════════════════════════"
echo "  Maestro Infrastructure Setup"
echo "═══════════════════════════════════════════"
echo ""

install_docker
check_docker_compose
generate_env
start_stack
print_summary
